# Generated by Django 4.1 on 2022-08-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chatid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chatId',
            new_name='chatid',
        ),
    ]
