# Generated by Django 4.1 on 2022-08-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chat_partida_id'),
        ('users', '0008_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chatid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
