# Generated by Django 4.1 on 2022-08-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_remove_partida_usuario_partida_usuarioid'),
        ('users', '0009_alter_user_chatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partidaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidas.partida'),
        ),
    ]
