# Generated by Django 4.1 on 2022-08-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juegoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juegos')),
            ],
        ),
    ]
