# Generated by Django 4.1 on 2022-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
