# Generated by Django 4.1 on 2022-08-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chat_partida_id'),
        ('partidas', '0002_partida_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='chat_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
