# Generated by Django 4.1 on 2022-08-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        ('partidas', '0004_partida_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='juegoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.juegos'),
        ),
    ]
