# Generated by Django 4.1 on 2022-08-10 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidas', '0005_alter_partida_juegoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='usuario',
        ),
        migrations.AddField(
            model_name='partida',
            name='usuarioId',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
