# Generated by Django 4.1 on 2022-08-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_partida_nombre'),
        ('chat', '0004_remove_chat_partidas_chat_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='partida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidas.partida'),
        ),
    ]
