# Generated by Django 4.1 on 2022-08-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_partida_chat_partidaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='partidaId',
            new_name='partida',
        ),
    ]
