# Generated by Django 4.1 on 2022-08-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_partida_nombre'),
        ('chat', '0007_rename_partidaid_chat_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='partida',
        ),
        migrations.AddField(
            model_name='chat',
            name='partida_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidas.partida'),
        ),
    ]
