# Generated by Django 4.1 on 2022-08-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chat_partida_chat_partida_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='partida_id',
        ),
    ]
